# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yu7vzcblg28vc3BX9msqNZ-0xwiT75Te
"""

from model import Classifier, BasicBlock, ImagePreprocessor
import torch

def test_model():
    model = Classifier(BasicBlock, [2, 2, 2, 2])
    model.load_state_dict(torch.load("resnet18-f37072fd.pth"))
    model.eval()
    prep = ImagePreprocessor()
    img = prep.preprocess("sample.jpg")
    output = model(img)
    print(f"Predicted Class ID: {torch.argmax(output)}")

if __name__ == '__main__':
    test_model()